export enum QuantityProprety {
  AVAILABLE = 'AVAILABLE',
  DISCOVERED = 'DISCOVERED',
  RESERVED = 'RESERVED',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERY_PROCESSING = 'DELIVERY_PROCESSING',
  AWAITING_SAV = 'AWAITING_SAV',
  DELIVERED = 'DELIVERED',
  GOT_OUT = 'GOT_OUT',
  PENDING_INVESTIGATION = 'PENDING_INVESTIGATION',
  LOST = 'LOST',
  IS_DEAD = 'IS_DEAD',
  PENDING_RECEPTION = 'PENDING_RECEPTION',
}
