export enum MagentoFilterConditionType {
  EQUAL_VALUE = 'eq',
  NOT_EQUAL_VALUE = 'neq',
  LIKE_VALUE = 'like',
  NOT_LIKE_VALUE = 'nlike',
  IS_VALUE = 'is',
  IN_VALUES = 'in',
  NOT_IN_VALUES = 'nin',
  VALUE_IS_NOT_NULL = 'notnull',
  VALUE_IS_NULL = 'null',
  MORE_OR_EQUAL_VALUE = 'moreq',
  GREATER_VALUE = 'gt',
  LESS_VALUE = 'lt',
  GREATER_OR_EQUAL_VALUE = 'gteq',
  LESS_OR_EQUAL_VALUE = 'lteq',
  VALUE_IN_SET = 'finset',
  FROM_VALUE = 'from',
  TO_VALUE = 'to',
}
