export enum OutputType {
  FLEET_OUTPUT = 'FLEET_OUTPUT',
  PUS_OUTPUT = 'PUS_OUTPUT',
  SAV_OUTPUT = 'SAV_OUTPUT',
  SUPPLIER_OUTPUT = 'SUPPLIER_OUTPUT',
  B2B_OUTPUT = 'B2B_OUTPUT',
  INTERNAL_NEED = 'INTERNAL_NEED',
  OTHER_OUTPUT = 'OTHER_OUTPUT',
}
