export enum ReceptionType {
  TRANSFERT = 'TRANSFERT',
  CANCEL_TRANSFERT = 'CANCEL_TRANSFERT',
  PURCHASE_ORDER = 'PURCHASE_ORDER',
  ORDER = 'ORDER',
  DELIVERY_CANCELLATION = 'CA',
  INTERNAL_PROBLEM = 'IP',
  REJET_LIVRAISON = 'RJ',
  CUSTOMER_SERVICE = 'RS',
  AUTRE_ENTREE = 'AUTRE_ENTREE',
  INVENTORY = 'INVENTORY',
  UPDATED_ORDER = 'UPDATED_ORDER',
  CUSTOMER_RETURN = 'CUSTOMER_RETURN',
}
