export enum AreaDefaultType {
  RECEPTION = 'RECEPTION',
  AWAITING_SAV = 'AWAITING_SAV',
  DEAD_STOCK = 'DEAD_STOCK',
  PREPARATION = 'PREPARATION',
  DEPOT_VENTE = 'DEPOT_VENTE',
  OUTPUT = 'OUTPUT',
}
