export enum LocationDefaultType {
  SAV = 'SAV',
  RECEPTION = 'RECEPTION',
  AWAITING_SAV = 'AWAITING_SAV',
  DEAD_STOCK = 'DEAD_STOCK',
  INVESTIGATION = 'INVESTIGATION',
  PREPARATION = 'PREPARATION',
  DEPOT_VENTE = 'DEPOT_VENTE',
  PUS = 'PUS',
  FLEET = 'FLEET',
  EXPEDITION = 'EXPEDITION',
  INTERNAL_NEED = 'INTERNAL_NEED',
}
