export enum ExpeditionStatus {
  SENT = 'SENT',
  RECEPTION_IN_PROGRESS = 'RECEPTION_IN_PROGRESS',
  PROCESSING = 'PROCESSING',
  PENDING = 'PENDING',
  RECIEVED = 'RECIEVED',
  CANCELED = 'CANCELED',
}