export const FmcgCategories = {
  main: {
    id: 1266,
    parent_id: 2,
    name: 'Supermarché',
    is_active: true,
    position: 1,
    level: 2,
    product_count: 2826,
    childrens: [
      {
        id: 1066,
        parent_id: 1266,
        name: 'Alimentaire',
        is_active: true,
        position: 1,
        level: 3,
        product_count: 755,
        childrens: [
          {
            id: 1350,
            parent_id: 1066,
            name: 'Pâte alimentaires Et Riz',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 166,
            childrens: [],
          },
          {
            id: 1313,
            parent_id: 1066,
            name: 'Huile, Vinaigre Et Vinaigrettes',
            is_active: true,
            position: 2,
            level: 4,
            product_count: 95,
            childrens: [],
          },
          {
            id: 1379,
            parent_id: 1066,
            name: 'Céréales',
            is_active: true,
            position: 3,
            level: 4,
            product_count: 73,
            childrens: [],
          },
          {
            id: 1285,
            parent_id: 1066,
            name: 'Conserves',
            is_active: true,
            position: 4,
            level: 4,
            product_count: 97,
            childrens: [
              {
                id: 1321,
                parent_id: 1285,
                name: 'Fruits',
                is_active: true,
                position: 1,
                level: 5,
                product_count: 15,
                childrens: [],
              },
              {
                id: 1322,
                parent_id: 1285,
                name: 'Viande',
                is_active: true,
                position: 1,
                level: 5,
                product_count: 6,
                childrens: [],
              },
              {
                id: 1323,
                parent_id: 1285,
                name: 'Poisson',
                is_active: true,
                position: 1,
                level: 5,
                product_count: 4,
                childrens: [],
              },
              {
                id: 1324,
                parent_id: 1285,
                name: 'Légumes',
                is_active: true,
                position: 1,
                level: 5,
                product_count: 22,
                childrens: [],
              },
              {
                id: 1332,
                parent_id: 1285,
                name: 'Autres',
                is_active: true,
                position: 1,
                level: 5,
                product_count: 19,
                childrens: [],
              },
            ],
          },
          {
            id: 1301,
            parent_id: 1066,
            name: 'Chocolats Et Bonbons',
            is_active: true,
            position: 5,
            level: 4,
            product_count: 56,
            childrens: [],
          },
          {
            id: 2326,
            parent_id: 1066,
            name: 'Chips',
            is_active: true,
            position: 6,
            level: 4,
            product_count: 22,
            childrens: [],
          },
          {
            id: 1345,
            parent_id: 1066,
            name: 'Sels, Epices et Bouillons ',
            is_active: true,
            position: 7,
            level: 4,
            product_count: 38,
            childrens: [],
          },
          {
            id: 1468,
            parent_id: 1066,
            name: 'laits en liquide',
            is_active: true,
            position: 8,
            level: 4,
            product_count: 21,
            childrens: [],
          },
          {
            id: 1583,
            parent_id: 1066,
            name: 'Sucre ',
            is_active: true,
            position: 9,
            level: 4,
            product_count: 11,
            childrens: [],
          },
          {
            id: 1389,
            parent_id: 1066,
            name: 'Farines, Levures et Aromes ',
            is_active: true,
            position: 10,
            level: 4,
            product_count: 33,
            childrens: [],
          },
          {
            id: 1326,
            parent_id: 1066,
            name: 'Beurres et Fromages ',
            is_active: true,
            position: 11,
            level: 4,
            product_count: 41,
            childrens: [],
          },
          {
            id: 1341,
            parent_id: 1066,
            name: 'Petit déjeuner',
            is_active: true,
            position: 12,
            level: 4,
            product_count: 157,
            childrens: [
              {
                id: 1342,
                parent_id: 1341,
                name: 'Tartine',
                is_active: true,
                position: 1,
                level: 5,
                product_count: 46,
                childrens: [],
              },
              {
                id: 1343,
                parent_id: 1341,
                name: 'Charcuterie',
                is_active: true,
                position: 1,
                level: 5,
                product_count: 2,
                childrens: [],
              },
              {
                id: 1344,
                parent_id: 1341,
                name: 'Céréales et corn-flake',
                is_active: true,
                position: 1,
                level: 5,
                product_count: 11,
                childrens: [],
              },
              {
                id: 1789,
                parent_id: 1341,
                name: 'Pack déjeuner',
                is_active: true,
                position: 1,
                level: 5,
                product_count: 43,
                childrens: [],
              },
              {
                id: 1894,
                parent_id: 1341,
                name: 'Miel',
                is_active: true,
                position: 2,
                level: 5,
                product_count: 10,
                childrens: [],
              },
              {
                id: 1316,
                parent_id: 1341,
                name: 'Mayonnaise',
                is_active: true,
                position: 3,
                level: 5,
                product_count: 18,
                childrens: [],
              },
              {
                id: 1315,
                parent_id: 1341,
                name: 'Ketchup',
                is_active: true,
                position: 4,
                level: 5,
                product_count: 11,
                childrens: [],
              },
            ],
          },
        ],
      },
      {
        id: 1270,
        parent_id: 1266,
        name: 'Boisson Alcoolisées',
        is_active: true,
        position: 2,
        level: 3,
        product_count: 827,
        childrens: [
          {
            id: 1271,
            parent_id: 1270,
            name: 'Vins',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 299,
            childrens: [],
          },
          {
            id: 1272,
            parent_id: 1270,
            name: 'Liqueurs',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 70,
            childrens: [],
          },
          {
            id: 1273,
            parent_id: 1270,
            name: 'Spiritueux',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 211,
            childrens: [],
          },
          {
            id: 1274,
            parent_id: 1270,
            name: 'Bières',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 14,
            childrens: [],
          },
          {
            id: 1451,
            parent_id: 1270,
            name: 'Vins Mousseur',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 53,
            childrens: [],
          },
          {
            id: 1275,
            parent_id: 1270,
            name: 'Boissons Gazeuses ',
            is_active: true,
            position: 2,
            level: 4,
            product_count: 43,
            childrens: [],
          },
          {
            id: 2466,
            parent_id: 1270,
            name: "Grant's",
            is_active: true,
            position: 3,
            level: 4,
            product_count: 19,
            childrens: [],
          },
          {
            id: 1277,
            parent_id: 1270,
            name: 'Eau minerale',
            is_active: true,
            position: 4,
            level: 4,
            product_count: 18,
            childrens: [],
          },
          {
            id: 2467,
            parent_id: 1270,
            name: 'Jus de Fruits Naturels ',
            is_active: true,
            position: 5,
            level: 4,
            product_count: 20,
            childrens: [],
          },
          {
            id: 1538,
            parent_id: 1270,
            name: 'Packs à ne pas manquer',
            is_active: true,
            position: 6,
            level: 4,
            product_count: 33,
            childrens: [],
          },
          {
            id: 1335,
            parent_id: 1270,
            name: 'Champagnes et Vin Mousseux ',
            is_active: true,
            position: 7,
            level: 4,
            product_count: 57,
            childrens: [],
          },
          {
            id: 1276,
            parent_id: 1270,
            name: 'Non gazeuses',
            is_active: true,
            position: 8,
            level: 4,
            product_count: 47,
            childrens: [],
          },
          {
            id: 2337,
            parent_id: 1270,
            name: 'La Cave De Glo',
            is_active: true,
            position: 9,
            level: 4,
            product_count: 124,
            childrens: [],
          },
        ],
      },
      {
        id: 1282,
        parent_id: 1266,
        name: 'Entretien et Nettoyages ',
        is_active: true,
        position: 3,
        level: 3,
        product_count: 387,
        childrens: [
          {
            id: 1296,
            parent_id: 1282,
            name: 'Détergent',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 79,
            childrens: [],
          },
          {
            id: 1297,
            parent_id: 1282,
            name: 'Désodorisants et insecticides ',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 35,
            childrens: [],
          },
          {
            id: 1298,
            parent_id: 1282,
            name: 'Adoucissant',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 51,
            childrens: [],
          },
          {
            id: 1299,
            parent_id: 1282,
            name: 'Liquide Nettoyants ',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 103,
            childrens: [],
          },
          {
            id: 1336,
            parent_id: 1282,
            name: 'Divers',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 29,
            childrens: [],
          },
          {
            id: 1543,
            parent_id: 1282,
            name: 'Savon en Morceau',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 19,
            childrens: [],
          },
          {
            id: 1305,
            parent_id: 1282,
            name: 'Essuie tout , Papier toilette et Mouchoirs ',
            is_active: true,
            position: 2,
            level: 4,
            product_count: 28,
            childrens: [],
          },
          {
            id: 1306,
            parent_id: 1282,
            name: 'Autres',
            is_active: true,
            position: 3,
            level: 4,
            product_count: 30,
            childrens: [],
          },
        ],
      },
      {
        id: 1283,
        parent_id: 1266,
        name: 'Toilette',
        is_active: true,
        position: 4,
        level: 3,
        product_count: 72,
        childrens: [
          {
            id: 1288,
            parent_id: 1283,
            name: 'Dentifrice',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 3,
            childrens: [],
          },
          {
            id: 1289,
            parent_id: 1283,
            name: 'Déodorant',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 22,
            childrens: [],
          },
          {
            id: 1290,
            parent_id: 1283,
            name: 'Gels de douche',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 11,
            childrens: [],
          },
          {
            id: 1292,
            parent_id: 1283,
            name: 'Crème dépilant',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 2,
            childrens: [],
          },
          {
            id: 1293,
            parent_id: 1283,
            name: 'Parfum',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 23,
            childrens: [],
          },
          {
            id: 1295,
            parent_id: 1283,
            name: 'Autre accessoires',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 8,
            childrens: [],
          },
        ],
      },
      {
        id: 1278,
        parent_id: 1266,
        name: 'Enfants et Nourissons ',
        is_active: true,
        position: 5,
        level: 3,
        product_count: 316,
        childrens: [
          {
            id: 1466,
            parent_id: 1278,
            name: 'Laits et Céréales ',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 88,
            childrens: [],
          },
          {
            id: 1294,
            parent_id: 1278,
            name: 'Gamme de Toilette ',
            is_active: true,
            position: 2,
            level: 4,
            product_count: 168,
            childrens: [],
          },
          {
            id: 1358,
            parent_id: 1278,
            name: 'Accessoires entretien ',
            is_active: true,
            position: 3,
            level: 4,
            product_count: 0,
            childrens: [],
          },
          {
            id: 1287,
            parent_id: 1278,
            name: 'Couche et lingette  Bébé ',
            is_active: true,
            position: 4,
            level: 4,
            product_count: 59,
            childrens: [],
          },
        ],
      },
      {
        id: 1268,
        parent_id: 1266,
        name: 'Boisson Chaud',
        is_active: true,
        position: 6,
        level: 3,
        product_count: 81,
        childrens: [
          {
            id: 1279,
            parent_id: 1268,
            name: 'Café',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 44,
            childrens: [],
          },
          {
            id: 1280,
            parent_id: 1268,
            name: 'Thé',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 35,
            childrens: [],
          },
        ],
      },
      {
        id: 1269,
        parent_id: 1266,
        name: 'boissons alcoolisée',
        is_active: true,
        position: 6,
        level: 3,
        product_count: 54,
        childrens: [],
      },
      {
        id: 1284,
        parent_id: 1266,
        name: 'Mouchoirs et Accessoires Divers',
        is_active: true,
        position: 6,
        level: 3,
        product_count: 22,
        childrens: [
          {
            id: 1303,
            parent_id: 1284,
            name: 'Papiers Alu',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 3,
            childrens: [],
          },
          {
            id: 1385,
            parent_id: 1284,
            name: 'plastiques poubelles',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 4,
            childrens: [],
          },
          {
            id: 1387,
            parent_id: 1284,
            name: 'Plastiques de Congélation',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 1,
            childrens: [],
          },
          {
            id: 1442,
            parent_id: 1284,
            name: 'Papiers Hygiénique',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 11,
            childrens: [],
          },
          {
            id: 1869,
            parent_id: 1284,
            name: 'Emballages',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 1,
            childrens: [],
          },
        ],
      },
      {
        id: 1300,
        parent_id: 1266,
        name: 'Confiseries et Biscuiterie',
        is_active: true,
        position: 6,
        level: 3,
        product_count: 103,
        childrens: [
          {
            id: 1302,
            parent_id: 1300,
            name: 'Corn-flakes',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 3,
            childrens: [],
          },
          {
            id: 1346,
            parent_id: 1300,
            name: 'Biscuits',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 83,
            childrens: [],
          },
        ],
      },
      {
        id: 1308,
        parent_id: 1266,
        name: 'Épices et Aromates',
        is_active: true,
        position: 6,
        level: 3,
        product_count: 43,
        childrens: [
          {
            id: 1325,
            parent_id: 1308,
            name: 'Cubes',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 4,
            childrens: [],
          },
          {
            id: 1327,
            parent_id: 1308,
            name: 'Poivre',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 5,
            childrens: [],
          },
          {
            id: 1329,
            parent_id: 1308,
            name: 'Menthe',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 1,
            childrens: [],
          },
          {
            id: 1330,
            parent_id: 1308,
            name: 'Curry',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 1,
            childrens: [],
          },
          {
            id: 1331,
            parent_id: 1308,
            name: 'Autres',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 15,
            childrens: [],
          },
          {
            id: 1453,
            parent_id: 1308,
            name: 'Arômes',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 9,
            childrens: [],
          },
        ],
      },
      {
        id: 1309,
        parent_id: 1266,
        name: 'Sauces et Légumes',
        is_active: true,
        position: 6,
        level: 3,
        product_count: 21,
        childrens: [
          {
            id: 1314,
            parent_id: 1309,
            name: 'Assaisonnement divers',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 8,
            childrens: [],
          },
          {
            id: 1317,
            parent_id: 1309,
            name: 'Tomate',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 2,
            childrens: [],
          },
          {
            id: 1318,
            parent_id: 1309,
            name: 'Moutarde',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 4,
            childrens: [],
          },
        ],
      },
      {
        id: 1333,
        parent_id: 1266,
        name: 'Autres',
        is_active: true,
        position: 6,
        level: 3,
        product_count: 10,
        childrens: [],
      },
      {
        id: 1337,
        parent_id: 1266,
        name: 'Autres',
        is_active: true,
        position: 6,
        level: 3,
        product_count: 17,
        childrens: [
          {
            id: 1787,
            parent_id: 1337,
            name: ' Sélection pack Supermarcher',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 8,
            childrens: [],
          },
        ],
      },
      {
        id: 1348,
        parent_id: 1266,
        name: 'Céréales et Graines',
        is_active: true,
        position: 6,
        level: 3,
        product_count: 144,
        childrens: [
          {
            id: 1349,
            parent_id: 1348,
            name: 'Riz',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 85,
            childrens: [],
          },
          {
            id: 1351,
            parent_id: 1348,
            name: 'Haricot',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 1,
            childrens: [],
          },
          {
            id: 1352,
            parent_id: 1348,
            name: 'Arachide',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 2,
            childrens: [],
          },
          {
            id: 1353,
            parent_id: 1348,
            name: 'Pistache',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            childrens: [],
          },
          {
            id: 1354,
            parent_id: 1348,
            name: 'Soja',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            childrens: [],
          },
          {
            id: 1355,
            parent_id: 1348,
            name: 'Blé',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 22,
            childrens: [],
          },
          {
            id: 1447,
            parent_id: 1348,
            name: 'Céréales',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 22,
            childrens: [],
          },
          {
            id: 1852,
            parent_id: 1348,
            name: 'Ma Pâtisserie En Confinement',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 0,
            childrens: [],
          },
        ],
      },
      {
        id: 1393,
        parent_id: 1266,
        name: 'Huile de Cuisine',
        is_active: true,
        position: 6,
        level: 3,
        product_count: 39,
        childrens: [
          {
            id: 1396,
            parent_id: 1393,
            name: 'Huile de Soja',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 4,
            childrens: [],
          },
          {
            id: 1398,
            parent_id: 1393,
            name: 'Huile de Palm',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 6,
            childrens: [],
          },
          {
            id: 1401,
            parent_id: 1393,
            name: 'Huile de Coton',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 2,
            childrens: [],
          },
          {
            id: 1404,
            parent_id: 1393,
            name: 'Huile de Tournesol',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 3,
            childrens: [],
          },
          {
            id: 1406,
            parent_id: 1393,
            name: "Huile d'olive",
            is_active: true,
            position: 1,
            level: 4,
            product_count: 11,
            childrens: [],
          },
          {
            id: 1410,
            parent_id: 1393,
            name: 'Autres',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 10,
            childrens: [],
          },
        ],
      },
      {
        id: 1977,
        parent_id: 1266,
        name: 'Produits BVS',
        is_active: true,
        position: 6,
        level: 3,
        product_count: 182,
        childrens: [
          {
            id: 2585,
            parent_id: 1977,
            name: 'Les Jus BVS',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 13,
            childrens: [],
          },
          {
            id: 2586,
            parent_id: 1977,
            name: 'Vins  Blancs BVS',
            is_active: true,
            position: 2,
            level: 4,
            product_count: 18,
            childrens: [],
          },
          {
            id: 2587,
            parent_id: 1977,
            name: 'Vins  Rouge BVS',
            is_active: true,
            position: 3,
            level: 4,
            product_count: 10,
            childrens: [],
          },
          {
            id: 2588,
            parent_id: 1977,
            name: 'Builles BVS',
            is_active: true,
            position: 4,
            level: 4,
            product_count: 6,
            childrens: [],
          },
          {
            id: 2589,
            parent_id: 1977,
            name: 'Whisky BVS',
            is_active: true,
            position: 5,
            level: 4,
            product_count: 18,
            childrens: [],
          },
          {
            id: 2592,
            parent_id: 1977,
            name: 'Vins  Rosées BVS',
            is_active: true,
            position: 6,
            level: 4,
            product_count: 4,
            childrens: [],
          },
        ],
      },
      {
        id: 2157,
        parent_id: 1266,
        name: 'Offre Boisson',
        is_active: true,
        position: 6,
        level: 3,
        product_count: 7,
        childrens: [],
      },
      {
        id: 2338,
        parent_id: 1266,
        name: 'Africa Trade Company',
        is_active: true,
        position: 6,
        level: 3,
        product_count: 21,
        childrens: [],
      },
      {
        id: 2384,
        parent_id: 1266,
        name: 'Offre Spéciale Supermarché',
        is_active: true,
        position: 6,
        level: 3,
        product_count: 21,
        childrens: [],
      },
      {
        id: 2462,
        parent_id: 1266,
        name: 'Diageo',
        is_active: true,
        position: 6,
        level: 3,
        product_count: 63,
        childrens: [],
      },
      {
        id: 2489,
        parent_id: 1266,
        name: 'Produit Olam',
        is_active: true,
        position: 6,
        level: 3,
        product_count: 6,
        childrens: [],
      },
      {
        id: 2496,
        parent_id: 1266,
        name: 'Africa Food Distribution',
        is_active: true,
        position: 7,
        level: 3,
        product_count: 140,
        childrens: [
          {
            id: 2497,
            parent_id: 2496,
            name: 'Alimentaire Brôli',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 112,
            childrens: [],
          },
          {
            id: 2490,
            parent_id: 2496,
            name: 'Spécial Vins',
            is_active: true,
            position: 2,
            level: 4,
            product_count: 17,
            childrens: [],
          },
          {
            id: 2499,
            parent_id: 2496,
            name: 'Lancement Africa Food',
            is_active: true,
            position: 3,
            level: 4,
            product_count: 20,
            childrens: [],
          },
        ],
      },
      {
        id: 2502,
        parent_id: 1266,
        name: 'Produit Beauté ',
        is_active: true,
        position: 8,
        level: 3,
        product_count: 84,
        childrens: [],
      },
      {
        id: 2526,
        parent_id: 1266,
        name: 'Grand Destockage des Vins',
        is_active: true,
        position: 9,
        level: 3,
        product_count: 79,
        childrens: [],
      },
      {
        id: 1764,
        parent_id: 1266,
        name: 'Nestlé Cameroun',
        is_active: true,
        position: 10,
        level: 3,
        product_count: 44,
        childrens: [
          {
            id: 1304,
            parent_id: 1764,
            name: 'Lait  Nestlé',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 33,
            childrens: [],
          },
          {
            id: 1291,
            parent_id: 1764,
            name: 'Aromes & Cubes',
            is_active: true,
            position: 2,
            level: 4,
            product_count: 6,
            childrens: [],
          },
          {
            id: 1328,
            parent_id: 1764,
            name: 'Nestcafé',
            is_active: true,
            position: 3,
            level: 4,
            product_count: 4,
            childrens: [],
          },
        ],
      },
      {
        id: 1452,
        parent_id: 1266,
        name: 'Campagne Supermarché',
        is_active: true,
        position: 11,
        level: 3,
        product_count: 0,
        childrens: [],
      },
      {
        id: 1595,
        parent_id: 1266,
        name: 'Le Repaire Du Bon Vin',
        is_active: true,
        position: 12,
        level: 3,
        product_count: 53,
        childrens: [],
      },
      {
        id: 1599,
        parent_id: 1266,
        name: 'Super deals ',
        is_active: true,
        position: 13,
        level: 3,
        product_count: 16,
        childrens: [],
      },
      {
        id: 2539,
        parent_id: 1266,
        name: 'Entretenons notre maison ',
        is_active: true,
        position: 14,
        level: 3,
        product_count: 39,
        childrens: [],
      },
      {
        id: 2460,
        parent_id: 1266,
        name: 'Source Du Pays',
        is_active: true,
        position: 15,
        level: 3,
        product_count: 37,
        childrens: [
          {
            id: 1261,
            parent_id: 2460,
            name: 'Eau Mineral Source Du Pays',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 5,
            childrens: [],
          },
          {
            id: 1262,
            parent_id: 2460,
            name: 'Boisson Gazeuse Source Du Pays',
            is_active: true,
            position: 2,
            level: 4,
            product_count: 26,
            childrens: [],
          },
          {
            id: 1260,
            parent_id: 2460,
            name: 'Laits Source Du Pays',
            is_active: true,
            position: 3,
            level: 4,
            product_count: 3,
            childrens: [],
          },
        ],
      },
      {
        id: 1230,
        parent_id: 1266,
        name: 'Chococam',
        is_active: true,
        position: 16,
        level: 3,
        product_count: 33,
        childrens: [
          {
            id: 1228,
            parent_id: 1230,
            name: 'Chocolats & Mambo',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 17,
            childrens: [],
          },
          {
            id: 1213,
            parent_id: 1230,
            name: 'Bonbon Chococam',
            is_active: true,
            position: 2,
            level: 4,
            product_count: 7,
            childrens: [],
          },
          {
            id: 1223,
            parent_id: 1230,
            name: 'chewing-gum Chococam',
            is_active: true,
            position: 3,
            level: 4,
            product_count: 5,
            childrens: [],
          },
        ],
      },
      {
        id: 1971,
        parent_id: 1266,
        name: 'Boutique Officielle Ok Food ',
        is_active: true,
        position: 17,
        level: 3,
        product_count: 26,
        childrens: [],
      },
      {
        id: 2545,
        parent_id: 1266,
        name: 'Boutique OK FOODS',
        is_active: true,
        position: 18,
        level: 3,
        product_count: 26,
        childrens: [
          {
            id: 1226,
            parent_id: 2545,
            name: 'Biscuits Ok Food ',
            is_active: true,
            position: 1,
            level: 4,
            product_count: 8,
            childrens: [],
          },
          {
            id: 1165,
            parent_id: 2545,
            name: 'Bonbons Ok Food ',
            is_active: true,
            position: 2,
            level: 4,
            product_count: 12,
            childrens: [],
          },
          {
            id: 1218,
            parent_id: 2545,
            name: 'Laits Ok Food',
            is_active: true,
            position: 3,
            level: 4,
            product_count: 6,
            childrens: [],
          },
        ],
      },
    ],
  },
};
