export enum PurchaseStatusLine {
  SELLER_DELAY = 'SELLER_DELAY',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  PRICE_ISSUE = 'PRICE_ISSUE',
  AWAITING_CATMAN = 'AWAITING_CATMAN',
  NOT_BOUGHT = 'NOT_BOUGHT',
}
