export enum OrderSource {
  CUSTOMER_RETURN = 'CUSTOMER_RETURN',
  DEAD_LOCATION = 'DEAD_LOCATION',
  PUS_PICK_AND_COLLECT = 'PUS_PICK_AND_COLLECT',
  DESTOCKAGE = 'DESTOCKAGE',
  FLEET = 'FLEET',
  EXPEDITION = 'EXPEDITION',
  PUS = 'PUS',
}
